import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tentang",
  description: "Generated by create next app",
};

const TentangPage = () => {
  return (
    <div>
      <p>tentang</p>
    </div>
  );
};

export default TentangPage;
