import type { Metadata } from "next";
import "./globals.css";
import Nav from "./_components/navigation";
import Breadcrumb from "./_components/breadcrumbs";

export const metadata: Metadata = {
  title: { template: "%s | Inready Workgroup", default: "Inready Workgroup" },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <div className="pt-[80px] max-w-6xl mx-auto">
          <Breadcrumb />
          {children}
        </div>
      </body>
    </html>
  );
}
