import { Metadata } from "next";
import Image from "next/image";
import gambarIconDesign from "@/assets/icons/pen-tool 1.svg";
import gambarIconWeb from "@/assets/icons/website-content 1.svg";
import gambarIconMobile from "@/assets/icons/conding.svg";

export const metadata: Metadata = {
    title: "Tentang",
    description: "Generated by create next app",
};

const concentrationData = [
    {
        id: 1,
        title: "Web Development",
        description:
            "Fokus pada pengembangan aplikasi berbasis web yang responsif dan dinamis. Mempelajari teknologi Frontend dan Backend modern untuk membangun website yang handal.",
        icon: gambarIconWeb,
    },
    {
        id: 2,
        title: "Mobile Development",
        description:
            "Mempelajari cara merancang dan membangun aplikasi seluler (Android/iOS). Fokus pada penciptaan solusi digital yang dapat diakses langsung melalui genggaman pengguna.",
        icon: gambarIconMobile,
    },
    {
        id: 3,
        title: "UI/UX Design",
        description:
            "Mendalami seni merancang antarmuka (UI) yang estetis dan pengalaman pengguna (UX) yang intuitif. Belajar mengubah ide kompleks menjadi desain produk yang mudah digunakan.",
        icon: gambarIconDesign,
    },
];

const TentangPage = () => {
    return (
        <div>
            <div className="w-full text-justify text-sm md:text-base">
                <p className="text-left text-2xl font-medium text-secondary">
                    Tentang Inready Workgroup
                </p>
                <div className="mt-9 flex flex-col gap-9 text-greyCol">
                    <div className="space-y-5">
                        <h1 className="text-xl font-medium text-secondary">
                            Inready Workgroup
                        </h1>
                        <p className="indent-[35px]">
                            study club sebagai media mewujudkan pengembangan
                            wawasan dan kemampuan baik itu dalam bidang IT
                            maupun keorganisasian anggotanya.
                        </p>
                    </div>
                    <div className="space-y-5">
                        <h1 className="text-xl font-medium text-secondary">
                            Kenapa Kami Ada?
                        </h1>
                        <p className="indent-[35px]">
                            Inready Workgroup hadir sebagai sebuah study club
                            yang Mewadahi dan mengorganisir semua mahasiswa UIN
                            Alauddin Makassar yang terlingkup dalam INREADY
                            WORKGROUP agar memiliki kecakapan pengetahuan di
                            bidang IT.
                        </p>
                    </div>
                    <div className="">
                        <h1 className="text-xl font-medium text-secondary">
                            Tujuan
                        </h1>
                        <p className="mt-2 indent-[35px]">
                            INREADY WORKGROUP bertujuan untuk:
                        </p>
                        <ol className="list-decimal">
                            <li>
                                Mengembangkan wawasan dan kemampuan anggota
                                INREADY WORKGROUP dalam bidang IT.
                            </li>
                            <li>
                                Menanamkan aspek pengembangan diri
                                keorganisasian pada setiap anggota INREADY
                                WORKGROUP.
                            </li>
                            <li>
                                Membangun jaringan kerjasama mutualisme semua
                                anggota INREADY WORKGROUP ke arah profesional.
                            </li>
                        </ol>
                    </div>
                </div>
                <p className="mt-10 text-xl font-semibold">
                    Konsentrasi yang ditawarkan
                </p>

                <div className="mt-10 grid grid-cols-1 gap-x-7 gap-y-6 lg:grid-cols-3">
                    {concentrationData.map((item, index) => (
                        <div
                            className="h-[328px] w-full rounded-3xl px-8 py-9 shadow-[0px_24px_32px_-3px_rgba(3,_9,_50,_0.04)] bg-white transition-all hover:shadow-lg"
                            key={index}
                        >
                            <div className="flex aspect-square  justify-center rounded-full bg-primary/20 p-4 relative w-4 h-4">
                                <Image
                                    src={item.icon}
                                    alt={item.title}
                                    width={8}
                                    height={8}
                                />
                                <div className="h-6 w-6 rounded-full bg-primary" />
                            </div>

                            <div className="mt-7 flex flex-col gap-5">
                                <p className="text-lg font-medium text-secondary">
                                    {item.title}
                                </p>
                                <p className="text-[12px] leading-[22px] text-greyCol line-clamp-4">
                                    {item.description}
                                </p>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};

export default TentangPage;
