import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Tentang",
    description: "Generated by create next app",
};

const TentangPage = () => {
    return (
        <div>
            <div className="w-full text-justify text-sm md:text-base">
                <p className="text-left text-2xl font-medium text-secondary">
                    Tentang Inready Workgroup
                </p>
                <div className="mt-9 flex flex-col gap-9 text-greyCol">
                    <div className="space-y-5">
                        <h1 className="text-xl font-medium text-secondary">
                            Inready Workgroup
                        </h1>
                        <p className="indent-[35px]">
                            study club sebagai media mewujudkan pengembangan
                            wawasan dan kemampuan baik itu dalam bidang IT
                            maupun keorganisasian anggotanya.
                        </p>
                    </div>
                    <div className="space-y-5">
                        <h1 className="text-xl font-medium text-secondary">
                            Kenapa Kami Ada?
                        </h1>
                        <p className="indent-[35px]">
                            Inready Workgroup hadir sebagai sebuah study club
                            yang Mewadahi dan mengorganisir semua mahasiswa UIN
                            Alauddin Makassar yang terlingkup dalam INREADY
                            WORKGROUP agar memiliki kecakapan pengetahuan di
                            bidang IT.
                        </p>
                    </div>
                    <div className="">
                        <h1 className="text-xl font-medium text-secondary">
                            Tujuan
                        </h1>
                        <p className="mt-2 indent-[35px]">
                            INREADY WORKGROUP bertujuan untuk:
                        </p>
                        <ol className="list-decimal">
                            <li>
                                Mengembangkan wawasan dan kemampuan anggota
                                INREADY WORKGROUP dalam bidang IT.
                            </li>
                            <li>
                                Menanamkan aspek pengembangan diri
                                keorganisasian pada setiap anggota INREADY
                                WORKGROUP.
                            </li>
                            <li>
                                Membangun jaringan kerjasama mutualisme semua
                                anggota INREADY WORKGROUP ke arah profesional.
                            </li>
                        </ol>
                    </div>
                </div>
                <p className="mt-10">Konsentrasi yang ditawarkan</p>
                <div className="mt-10 grid grid-cols-1 gap-x-7 lg:grid-cols-3">
                    {[1, 2, 3].map((_, index) => (
                        <div
                            className="h-[328px] w-full rounded-3xl px-8 py-9 shadow-[0px_24px_32px_-3px_rgba(3,_9,_50,_0.04)]"
                            key={index}
                        >
                            <div className="flex aspect-square w-fit justify-center rounded-full bg-primary/20 p-4">
                                {/* <img src={webIcon} alt="" className="w-3/4" /> */}
                            </div>
                            <div className="mt-7 flex flex-col gap-5">
                                <p className="text-sm font-medium text-secondary">
                                    Web Development
                                </p>
                                <p className="text-[10px] leading-[18px] text-greyCol">
                                    Belajar dunia desain web dan bangun karir
                                    yang menarik sebagai pengembang web.
                                </p>
                            </div>
                            {/* <Button title="Lihat Karya" className="mt-4" link="/karya" /> */}
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};

export default TentangPage;
